#!/usr/bin/env python3
"""Generate the catalog-derived documentation from `catalog/*.json`.

Documentation that is written by hand drifts. These two files are therefore
generated, and CI runs `--check` to fail the build when someone edits a tweak
without regenerating them.

    python scripts/generate_docs.py          # write the files
    python scripts/generate_docs.py --check  # exit 1 if they are out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import List

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "cli"))

from originos_toolkit.catalog import Catalog, Tweak, load_catalog  # noqa: E402
from originos_toolkit.ops import (  # noqa: E402
    inverse_action,
    probe_for,
    runs_without_shizuku,
    shell_calls,
)

BANNER = "<!-- Generated by scripts/generate_docs.py — do not edit by hand. -->"
REPO = "https://github.com/cameleonnbss/originos-toolkit"


def risk_emoji(risk: str) -> str:
    return {"low": "🟢", "medium": "🟡", "high": "🔴"}.get(risk, "⚪")


def render_tweaks(catalog: Catalog) -> str:
    lines: List[str] = [
        BANNER,
        "",
        "# Tweak reference",
        "",
        f"Every tweak shipped in [`catalog/tweaks.json`](../catalog/tweaks.json) "
        f"(catalog v{catalog.catalog_version}, updated {catalog.updated_at}).",
        "",
        "Each entry lists the exact commands it runs, what it needs, and how it is undone.",
        "Nothing here requires root.",
        "",
        "**Legend** — 🟢 low risk · 🟡 medium · 🔴 high · "
        "`settings` = works with the *modify system settings* access alone, no Shizuku · "
        "`shizuku` = the app needs Shizuku · `adb` = run the commands from a computer.",
        "",
        "## Works without Shizuku",
        "",
    ]

    shell_free = [t for t in catalog.tweaks if runs_without_shizuku(t)]
    if shell_free:
        lines += [
            f"**{len(shell_free)} of {len(catalog.tweaks)} tweaks never need the shell user.** "
            "They only touch the `system` namespace, which an ordinary app may write once you "
            "grant *Settings → Apps → Special access → Modify system settings*. That grant is a "
            "single toggle, so these work with no Shizuku, no root and no computer — this is the "
            "path to take if you would rather not install Shizuku at all.",
            "",
        ]
        for tweak in shell_free:
            lines.append(f"- `{tweak.id}` — {tweak.summary}")
    else:
        lines.append("None: every tweak in this catalog needs the shell user.")

    lines += [
        "",
        "## Index",
        "",
        "| Tweak | Category | Risk | Needs | Verified | Undo |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for tweak in catalog.tweaks:
        undo = "explicit" if tweak.revert else ("automatic" if tweak.is_reversible else "**not possible**")
        lines.append(
            f"| [`{tweak.id}`](#{tweak.id}) | {catalog.category_name(tweak.category)} "
            f"| {risk_emoji(tweak.risk)} {tweak.risk} | {tweak.requires} "
            f"| {'yes' if tweak.verified else '**no**'} | {undo} |"
        )

    if catalog.profiles:
        lines += ["", "## Profiles", "", "| Profile | Contents | What it is for |", "| --- | --- | --- |"]
        for profile in catalog.profiles:
            ids = ", ".join(f"`{t}`" for t in profile.tweaks)
            lines.append(f"| `{profile.id}` | {ids} | {profile.blurb} |")

    lines += ["", "---", "", "## Details", ""]

    for tweak in catalog.tweaks:
        lines += [
            f"### {tweak.id}",
            "",
            f"**{tweak.name}** — {risk_emoji(tweak.risk)} {tweak.risk} risk · "
            f"needs `{tweak.requires}`"
            + (" *(no Shizuku)*" if runs_without_shizuku(tweak) else "") + " · "
            f"{'verified on hardware' if tweak.verified else '**community-submitted, unverified**'}",
            "",
            tweak.summary,
            "",
        ]
        if tweak.details:
            lines += [tweak.details, ""]

        lines += ["**OriginOS compatibility:** " + (", ".join(f"`{o}`" for o in tweak.origin_os) or "any"), ""]

        for action in tweak.actions:
            probe = probe_for(action)
            if probe is not None:
                lines.append(f"- _read first:_ `adb shell {probe.render()}`")
            # Delta ops are resolved against a sample density so the reference
            # shows a concrete command; the real value comes from the device.
            for call in shell_calls(action, previous="460"):
                suffix = "  _(computed from your real density)_" if action.op == "wm_density_delta" else ""
                lines.append(f"- `adb shell {call.render()}`{suffix}")

        if tweak.revert:
            lines += ["", "**Explicit revert:**"]
            for action in tweak.revert:
                for call in shell_calls(action, previous=None):
                    lines.append(f"- `adb shell {call.render()}`")
        elif tweak.is_reversible:
            lines += [
                "",
                "**Revert:** the previous value is captured before the change and restored by "
                "`originos-toolkit revert` (or *Revert* in the app).",
            ]
        else:
            lines += [
                "",
                "**Revert:** not applicable — this is a one-shot action that does not change "
                "persistent state.",
            ]

        # Show that every op maps to something we can talk about.
        documented = []
        for action in tweak.actions:
            if action.op in ("settings_put", "settings_delete", "device_config_put"):
                documented.append(f"inverse={inverse_action(action, '<previous>').op}")
        if documented:
            lines += ["", f"<sub>{', '.join(documented)}</sub>"]

        lines += ["", "---", ""]

    return "\n".join(lines).rstrip() + "\n"


def render_awesome(catalog: Catalog) -> str:
    total = sum(len(section.entries) for section in catalog.awesome)
    lines: List[str] = [
        BANNER,
        "",
        "# Awesome OriginOS",
        "",
        f"A curated list of **{total}** tools for Vivo / iQOO devices running OriginOS "
        "(and FuntouchOS), with the access level each one needs stated up front.",
        "",
        "This is the same list the app shows on its **Discover** screen, shipped from "
        "[`catalog/awesome.json`](../catalog/awesome.json). It is community-maintained: "
        "if a project moved, was archived or a better alternative exists, open a pull request.",
        "",
        "## Access levels",
        "",
        "| Badge | Meaning |",
        "| --- | --- |",
        "| `NO-ROOT` | Works on a stock device, no root, no computer after the first setup. |",
        "| `ADB` | Needs a computer with `adb`, at least for the initial setup. |",
        "| `SHIZUKU` | Uses Shizuku to borrow the shell identity. |",
        "| `ROOT` | Listed for reference: needs root, a Magisk module or LSPosed. |",
        "",
        "> Nothing in this list is bundled, forked or modified by OriginOS Toolkit. Links point "
        "at the upstream project, and the descriptions are our own paraphrase of what it does.",
        "",
        "## Contents",
        "",
    ]

    for section in catalog.awesome:
        anchor = section.id
        lines.append(f"- [{section.name}](#{anchor})")
    lines.append("")

    for section in catalog.awesome:
        lines += [f'<a id="{section.id}"></a>', "", f"## {section.name}", ""]
        if section.blurb:
            lines += [f"_{section.blurb}_", ""]
        for entry in section.entries:
            lines += [
                f"### [{entry.name}]({entry.url}) — `{entry.access.upper()}`",
                "",
                entry.description,
                "",
                f"`{entry.repo}`" + (f" · tags: {', '.join(entry.tags)}" if entry.tags else ""),
                "",
            ]

    lines += [
        "## Contributing an entry",
        "",
        "1. It must be open source, or at least free to use, and hosted somewhere permanent.",
        "2. State the access level honestly: if it needs root, say so.",
        "3. Describe what it does in your own words. No marketing copy.",
        "4. Add it to `catalog/awesome.json`, then run `python scripts/generate_docs.py`.",
        "",
        f"Full project: [{REPO}]({REPO})",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the files are out of date")
    parser.add_argument("--catalog", help="catalog directory")
    args = parser.parse_args()

    catalog = load_catalog(args.catalog)
    targets = {
        REPO_ROOT / "docs" / "TWEAKS.md": render_tweaks(catalog),
        REPO_ROOT / "docs" / "AWESOME-ORIGINOS.md": render_awesome(catalog),
    }

    stale: List[Path] = []
    for path, content in targets.items():
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != content:
                stale.append(path)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        # Bytes, so the LF endings these generated files are diffed with in CI
        # are exactly what lands on disk on every platform.
        path.write_bytes(content.encode("utf-8"))
        print(f"wrote {path.relative_to(REPO_ROOT)} ({len(content.splitlines())} lines)")

    if args.check:
        if stale:
            print("documentation is out of date:", file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("\nrun: python scripts/generate_docs.py", file=sys.stderr)
            return 1
        print("documentation is up to date")

    return 0


if __name__ == "__main__":
    sys.exit(main())
